name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          

      - name: Install Pre-commit
        run: |
          pip install pre-commit

      - name: Run Pre-commit
        run: |
          pre-commit run --all-files
          
      - name: Install OWASP Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.4/dependency-check-10.0.4-release.zip
          unzip dependency-check-10.0.4-release.zip -d /opt/
          mv /opt/dependency-check /opt/dependency-check-install

      - name: Run OWASP Dependency-Check
        run: |
          /opt/dependency-check-install/bin/dependency-check.sh --project "simple" --format ALL --failOnCVSS 9
          
      - name: Scan Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      
      - name: Increase version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current version: ${VERSION}"
          PATCH=$(echo $VERSION | cut -d '.' -f 3 | cut -d '-' -f 1)
          echo "Current patch version: ${PATCH}"
          INCREASED_VERSION=1.0.$((PATCH + 1))-SNAPSHOT
          echo "Changing version to: ${INCREASED_VERSION}"
          mvn versions:set -DnewVersion=${INCREASED_VERSION}
          mvn versions:commit 
          cat pom.xml
      
          
      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: orgitlab
          password: ${{ secrets.DOCKER_PASSWORD }} # pragma: allowlist secret
      
      - name: Push Docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            orgitlab/hello:${{ github.sha }}
            orgitlab/hello:latest
            
      - name: Commit updated pom.xml
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add pom.xml
          git commit -m "Update pom.xml version"
          git pull origin master --rebase
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
