name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  
          
   #   - name: Increase version
   #     run: |
   #       VERSION=$( mvn help:evaluate -Dexpression=project.version -q)
   #       PATCH=$(echo $VERSION | cut -d '.' -f 3 | cut -d '-' -f 1)
   #       INCREASED_VERSION=1.0.$((PATCH +1))
   #       echo "Changing version to: ${INCREASED_VERSION}"
   #       mvn versions:set -DnewVersion=${INCREASED_VERSION}
   #       mvn versions:commit 
   #       cat pom.xml
                  
          
      - name: Build Docker image 
       run: |
           docker build -t orgitlab/hello:${{ github.sha }} .
      
      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: orgitlab
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            orgitlab/hello:${{ github.sha }}
            orgitlab/hello:latest 
      
